// muyue-ui/src/views/monitor/server/index.vue
<template>
  <div class="app-container">
    <div class="monitor-toolbar">
      <el-button :icon="Refresh" :loading="loading" @click="getServerInfo">刷新</el-button>
      <el-switch
        v-model="auto"
        active-text="自动刷新 (10s)"
        inline-prompt
        style="margin-left: 14px"
        @change="toggleAuto"
      />
    </div>

    <el-row :gutter="16">
      <!-- CPU -->
      <el-col :xs="24" :md="12" style="margin-bottom: 16px">
        <div class="page-container">
          <div class="section-title">CPU</div>
          <div class="gauge-wrap">
            <el-progress type="dashboard" :percentage="num(server.cpu.total)" :color="colorOf(server.cpu.total)" />
          </div>
          <el-descriptions :column="1" border size="small">
            <el-descriptions-item label="核心数">{{ server.cpu.cpuNum }}</el-descriptions-item>
            <el-descriptions-item label="用户使用率">{{ server.cpu.used }}%</el-descriptions-item>
            <el-descriptions-item label="系统使用率">{{ server.cpu.sys }}%</el-descriptions-item>
            <el-descriptions-item label="等待">{{ server.cpu.wait }}%</el-descriptions-item>
            <el-descriptions-item label="空闲">{{ server.cpu.free }}%</el-descriptions-item>
          </el-descriptions>
        </div>
      </el-col>

      <!-- 内存 -->
      <el-col :xs="24" :md="12" style="margin-bottom: 16px">
        <div class="page-container">
          <div class="section-title">内存</div>
          <div class="gauge-wrap">
            <el-progress type="dashboard" :percentage="num(server.mem.usage)" :color="colorOf(server.mem.usage)" />
          </div>
          <el-descriptions :column="1" border size="small">
            <el-descriptions-item label="总内存">{{ server.mem.total }} GB</el-descriptions-item>
            <el-descriptions-item label="已用">{{ server.mem.used }} GB</el-descriptions-item>
            <el-descriptions-item label="剩余">{{ server.mem.free }} GB</el-descriptions-item>
          </el-descriptions>
        </div>
      </el-col>
    </el-row>

    <el-row :gutter="16">
      <!-- 服务器信息 -->
      <el-col :xs="24" :md="12" style="margin-bottom: 16px">
        <div class="page-container">
          <div class="section-title">服务器信息</div>
          <el-descriptions :column="1" border size="small">
            <el-descriptions-item label="主机名称">{{ server.sys.computerName }}</el-descriptions-item>
            <el-descriptions-item label="IP 地址">{{ server.sys.computerIp }}</el-descriptions-item>
            <el-descriptions-item label="操作系统">{{ server.sys.osName }}</el-descriptions-item>
            <el-descriptions-item label="系统架构">{{ server.sys.osArch }}</el-descriptions-item>
            <el-descriptions-item label="运行目录">{{ server.sys.userDir }}</el-descriptions-item>
          </el-descriptions>
        </div>
      </el-col>

      <!-- JVM -->
      <el-col :xs="24" :md="12" style="margin-bottom: 16px">
        <div class="page-container">
          <div class="section-title">Java 虚拟机 (JVM)</div>
          <div class="gauge-wrap">
            <el-progress type="dashboard" :percentage="num(server.jvm.usage)" :color="colorOf(server.jvm.usage)" />
          </div>
          <el-descriptions :column="1" border size="small">
            <el-descriptions-item label="名称">{{ server.jvm.name }}</el-descriptions-item>
            <el-descriptions-item label="版本">{{ server.jvm.version }}</el-descriptions-item>
            <el-descriptions-item label="启动时间">{{ server.jvm.startTime }}</el-descriptions-item>
            <el-descriptions-item label="运行时长">{{ server.jvm.runTime }}</el-descriptions-item>
            <el-descriptions-item label="已用 / 最大">{{ server.jvm.used }} / {{ server.jvm.max }} MB</el-descriptions-item>
          </el-descriptions>
        </div>
      </el-col>
    </el-row>

    <!-- 磁盘 -->
    <div class="page-container" style="margin-bottom: 16px">
      <div class="section-title">磁盘状态</div>
      <el-table :data="server.sysFiles" border>
        <el-table-column label="盘符路径" prop="dirName" min-width="160" />
        <el-table-column label="文件系统" prop="sysTypeName" min-width="110" />
        <el-table-column label="盘符类型" prop="typeName" min-width="110" />
        <el-table-column label="总大小(GB)" prop="total" width="110" />
        <el-table-column label="可用(GB)" prop="free" width="110" />
        <el-table-column label="已用(GB)" prop="used" width="110" />
        <el-table-column label="使用率" min-width="200">
          <template #default="{ row }">
            <el-progress :percentage="num(row.usage)" :color="colorOf(row.usage)" :stroke-width="14" />
          </template>
        </el-table-column>
      </el-table>
    </div>
  </div>
</template>

<script setup>
import { onMounted, onUnmounted, reactive, ref } from 'vue'
import { Refresh } from '@element-plus/icons-vue'
import { getServer } from '@/api/monitor/server'

const loading = ref(false)
const auto = ref(false)
let timer = null
const server = reactive({ cpu: {}, mem: {}, sys: {}, jvm: {}, sysFiles: [] })

function num(v) {
  return Number(v || 0)
}
function colorOf(v) {
  const n = Number(v || 0)
  return n < 60 ? '#67c23a' : n < 85 ? '#e6a23c' : '#f56c6c'
}
function getServerInfo() {
  loading.value = true
  getServer()
    .then((res) => {
      Object.assign(server, res.data)
      loading.value = false
    })
    .catch(() => {
      loading.value = false
    })
}
function toggleAuto(v) {
  if (v) {
    timer = setInterval(getServerInfo, 10000)
  } else if (timer) {
    clearInterval(timer)
  }
}

onMounted(getServerInfo)
onUnmounted(() => {
  if (timer) clearInterval(timer)
})
</script>

<style scoped>
.app-container {
  padding: 18px;
}
.monitor-toolbar {
  display: flex;
  align-items: center;
  margin-bottom: 16px;
}
.gauge-wrap {
  display: flex;
  justify-content: center;
  padding: 6px 0;
}
</style>

// muyue-react-ui/src/pages/monitor/server.jsx
import React, { useEffect, useState } from 'react'
import { PageContainer, ProCard } from '@ant-design/pro-components'
import { Col, Descriptions, Progress, Row, Card, Table } from 'antd'
import { getServerInfo } from '../../api/tool'

const colorOf = (v) => (v >= 80 ? '#f5222d' : v >= 60 ? '#faad14' : '#52c41a')
const num = (v) => Math.min(Math.max(Number(v) || 0, 0), 100)

function Ring({ title, percent, children }) {
  return (
    <Card size="small" title={title}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 24 }}>
        <Progress type="dashboard" percent={num(percent)} strokeColor={colorOf(num(percent))} />
        <div style={{ flex: 1 }}>{children}</div>
      </div>
    </Card>
  )
}

export default function MonitorServer() {
  const [server, setServer] = useState(null)

  const load = () => getServerInfo().then((res) => setServer(res.data))
  useEffect(load, [])

  if (!server) return <PageContainer><Card loading /></PageContainer>

  return (
    <PageContainer>
      <Row gutter={16}>
        <Col span={8}>
          <Ring title="CPU 使用率" percent={server.cpu?.total}>
            <Descriptions column={1} size="small">
              <Descriptions.Item label="核心数">{server.cpu?.cpuNum}</Descriptions.Item>
              <Descriptions.Item label="用户 / 系统">{server.cpu?.used}% / {server.cpu?.sys}%</Descriptions.Item>
              <Descriptions.Item label="空闲">{server.cpu?.free}%</Descriptions.Item>
            </Descriptions>
          </Ring>
        </Col>
        <Col span={8}>
          <Ring title="内存使用率" percent={server.mem?.usage}>
            <Descriptions column={1} size="small">
              <Descriptions.Item label="总内存">{server.mem?.total} GB</Descriptions.Item>
              <Descriptions.Item label="已用 / 剩余">{server.mem?.used} / {server.mem?.free} GB</Descriptions.Item>
            </Descriptions>
          </Ring>
        </Col>
        <Col span={8}>
          <Ring title="JVM 使用率" percent={server.jvm?.usage}>
            <Descriptions column={1} size="small">
              <Descriptions.Item label="版本">{server.jvm?.version}</Descriptions.Item>
              <Descriptions.Item label="已用 / 最大">{server.jvm?.used} / {server.jvm?.max} MB</Descriptions.Item>
              <Descriptions.Item label="运行时长">{server.jvm?.runTime}</Descriptions.Item>
            </Descriptions>
          </Ring>
        </Col>
      </Row>

      <Row gutter={16} style={{ marginTop: 16 }}>
        <Col span={12}>
          <Card size="small" title="服务器信息">
            <Descriptions column={1} size="small">
              <Descriptions.Item label="服务器名称">{server.sys?.computerName}</Descriptions.Item>
              <Descriptions.Item label="操作系统">{server.sys?.osName}</Descriptions.Item>
              <Descriptions.Item label="服务器IP">{server.sys?.computerIp}</Descriptions.Item>
              <Descriptions.Item label="系统架构">{server.sys?.osArch}</Descriptions.Item>
            </Descriptions>
          </Card>
        </Col>
        <Col span={12}>
          <Card size="small" title="Java 虚拟机信息">
            <Descriptions column={1} size="small">
              <Descriptions.Item label="JVM 名称">{server.jvm?.name}</Descriptions.Item>
              <Descriptions.Item label="启动时间">{server.jvm?.startTime}</Descriptions.Item>
              <Descriptions.Item label="Java 版本">{server.jvm?.version}</Descriptions.Item>
              <Descriptions.Item label="Java 路径">{server.jvm?.home}</Descriptions.Item>
            </Descriptions>
          </Card>
        </Col>
      </Row>

      <Card size="small" title="磁盘状态" style={{ marginTop: 16 }}>
        <Table
          rowKey="dirName"
          size="small"
          pagination={false}
          dataSource={server.sysFiles || []}
          columns={[
            { title: '盘符路径', dataIndex: 'dirName' },
            { title: '文件系统', dataIndex: 'sysTypeName' },
            { title: '类型', dataIndex: 'typeName' },
            { title: '总大小', dataIndex: 'total' },
            { title: '可用大小', dataIndex: 'free' },
            { title: '已用大小', dataIndex: 'used' },
            {
              title: '已用百分比', dataIndex: 'usage', width: 180,
              render: (v) => <Progress percent={num(v)} strokeColor={colorOf(num(v))} size="small" />
            }
          ]}
        />
      </Card>
    </PageContainer>
  )
}
