// muyue-react-ui/src/pages/system/menu.jsx
import React, { useEffect, useState } from 'react'
import {
  PageContainer, ModalForm, ProFormText, ProFormRadio,
  ProFormTreeSelect, ProFormSelect, ProFormDigit, ProFormDependency
} from '@ant-design/pro-components'
import { App, Popconfirm, Space, Table, Tag } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { listMenu, getMenu, menuTreeSelect, addMenu, updateMenu, delMenu } from '../../api/menu'
import Auth from '../../components/Auth'

function toTreeData(nodes) {
  return (nodes || []).map((n) => ({
    title: n.label, value: n.id, key: n.id,
    children: toTreeData(n.children)
  }))
}

/** 扁平列表 → 树（后端 menu/list 返回平铺，需前端组树） */
function buildTree(list, idKey, parentKey) {
  const map = {}
  const input = list || []
  input.forEach((item) => {
    map[item[idKey]] = { ...item, key: item[idKey], children: [] }
  })
  const roots = []
  input.forEach((item) => {
    const node = map[item[idKey]]
    const parent = map[item[parentKey]]
    if (parent && item[parentKey] !== item[idKey]) {
      parent.children.push(node)
    } else {
      roots.push(node)
    }
  })
  const prune = (nodes) =>
    nodes.map((n) => {
      const next = { ...n }
      if (next.children.length) {
        next.children = prune(next.children)
      } else {
        delete next.children
      }
      return next
    })
  return prune(roots)
}

const typeTag = (v) => (
  <Tag color={v === 'M' ? 'geekblue' : v === 'C' ? 'cyan' : 'default'}>
    {v === 'M' ? '目录' : v === 'C' ? '菜单' : '按钮'}
  </Tag>
)

export default function SystemMenu() {
  const { message } = App.useApp()
  const [rows, setRows] = useState([])
  const [expandedKeys, setExpandedKeys] = useState([])
  const [loading, setLoading] = useState(true)
  const [formOpen, setFormOpen] = useState(false)
  const [editRow, setEditRow] = useState(null)
  const [treeData, setTreeData] = useState([])

  const collectKeys = (nodes) =>
    (nodes || []).flatMap((n) => (n.children && n.children.length ? [n.key, ...collectKeys(n.children)] : []))

  const load = () => {
    setLoading(true)
    listMenu().then((res) => {
      const tree = buildTree(res.data, 'menuId', 'parentId')
      setRows(tree)
      setExpandedKeys(collectKeys(tree))
      setLoading(false)
    })
  }

  useEffect(load, [])

  const openForm = async (row, parentId) => {
    setEditRow(row ? { ...row } : { parentId: parentId ?? 0, menuType: 'M', isFrame: '1', isCache: '0', visible: '0', status: '0' })
    setFormOpen(true)
    const tree = await menuTreeSelect()
    setTreeData(toTreeData(tree.data))
  }

  const columns = [
    { title: '菜单名称', dataIndex: 'menuName', width: 220 },
    { title: '图标', dataIndex: 'icon', width: 90, align: 'center', render: (v) => v && v !== '#' ? v : '-' },
    { title: '排序', dataIndex: 'orderNum', width: 70, align: 'center' },
    { title: '类型', dataIndex: 'menuType', width: 80, align: 'center', render: typeTag },
    { title: '权限字符', dataIndex: 'perms', width: 180, ellipsis: true },
    { title: '组件路径', dataIndex: 'component', width: 200, ellipsis: true },
    {
      title: '状态', dataIndex: 'status', width: 80, align: 'center',
      render: (v) => <Tag color={v === '0' ? 'success' : 'default'}>{v === '0' ? '正常' : '停用'}</Tag>
    },
    {
      title: '缓存', dataIndex: 'isCache', width: 90, align: 'center',
      render: (v, row) =>
        row.menuType === 'C'
          ? <Tag color={v === '0' ? 'blue' : 'default'}>{v === '0' ? '缓存' : '不缓存'}</Tag>
          : '-'
    },
    {
      title: '操作', width: 180,
      render: (_, row) => (
        <Space>
          {row.menuType !== 'F' && (
            <Auth permi="system:menu:add">
              <a onClick={() => openForm(null, row.menuId)}><PlusOutlined /> 新增</a>
            </Auth>
          )}
          <Auth permi="system:menu:edit">
            <a onClick={() => openForm(row)}>修改</a>
          </Auth>
          <Auth permi="system:menu:remove">
            <Popconfirm title="确认删除该菜单？" onConfirm={() =>
              delMenu(row.menuId).then(() => { message.success('删除成功'); load() })
            }>
              <a style={{ color: 'red' }}>删除</a>
            </Popconfirm>
          </Auth>
        </Space>
      )
    }
  ]

  return (
    <PageContainer>
      <div style={{ marginBottom: 12 }}>
        <Auth permi="system:menu:add">
          <a onClick={() => openForm(null, 0)}><PlusOutlined /> 新增顶级菜单</a>
        </Auth>
      </div>
      <Table
        rowKey="menuId"
        columns={columns}
        dataSource={rows}
        loading={loading}
        pagination={false}
        expandedKeys={expandedKeys}
        onExpandedRowsChange={setExpandedKeys}
      />

      <ModalForm
        title={editRow && editRow.menuId ? '修改菜单' : '新增菜单'}
        open={formOpen}
        onOpenChange={setFormOpen}
        width={620}
        modalProps={{ destroyOnClose: true }}
        initialValues={editRow}
        key={formOpen ? (editRow && editRow.menuId ? 'e' + editRow.menuId : 'a' + (editRow && editRow.parentId)) : 'closed'}
        onFinish={async (values) => {
          if (editRow && editRow.menuId) {
            await updateMenu({ menuId: editRow.menuId, parentId: editRow.parentId, ...values })
            message.success('修改成功')
          } else {
            await addMenu({ parentId: editRow.parentId, ...values })
            message.success('新增成功')
          }
          load()
          return true
        }}
      >
        <ProFormTreeSelect
          name="parentId" label="上级菜单"
          fieldProps={{ treeData, fieldNames: { label: 'title', value: 'value', children: 'children' } }}
          rules={[{ required: true }]}
        />
        <ProFormRadio.Group
          name="menuType" label="菜单类型"
          options={[{ label: '目录', value: 'M' }, { label: '菜单', value: 'C' }, { label: '按钮', value: 'F' }]}
          rules={[{ required: true }]}
        />
        <ProFormText name="menuName" label="菜单名称" rules={[{ required: true }]} />
        <ProFormText name="icon" label="图标" placeholder="Element 图标名，如 User" />
        <ProFormDigit name="orderNum" label="显示排序" min={0} rules={[{ required: true }]} />
        <ProFormText name="perms" label="权限字符" placeholder="如 system:user:list" />
        <ProFormText name="path" label="路由地址" placeholder="如 user" />
        <ProFormText name="component" label="组件路径" placeholder="如 system/user/index" />
        <ProFormRadio.Group
          name="status" label="状态"
          options={[{ label: '正常', value: '0' }, { label: '停用', value: '1' }]}
        />
        <ProFormDependency name={['menuType']}>
          {({ menuType }) =>
            menuType === 'C' && (
              <ProFormRadio.Group
                name="isCache" label="是否缓存"
                tooltip="开启后（keep-alive）切换页签保留查询条件与分页位置；页面组件名需与路由名一致"
                options={[{ label: '缓存', value: '0' }, { label: '不缓存', value: '1' }]}
              />
            )
          }
        </ProFormDependency>
      </ModalForm>
    </PageContainer>
  )
}

// muyue-ui/src/views/system/menu/index.vue
<template>
  <div class="page-container">
    <el-form :model="queryParams" :inline="true" class="search-form">
      <el-form-item label="菜单名称">
        <el-input v-model="queryParams.menuName" placeholder="请输入菜单名称" clearable style="width: 180px" @keyup.enter="handleQuery" />
      </el-form-item>
      <el-form-item label="状态">
        <el-select v-model="queryParams.status" placeholder="请选择" clearable style="width: 110px">
          <el-option label="正常" value="0" />
          <el-option label="停用" value="1" />
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
        <el-button icon="Refresh" @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <div class="table-toolbar">
      <el-button v-hasPermi="['system:menu:add']" type="primary" icon="Plus" @click="handleAdd">新增</el-button>
      <el-button icon="Sort" @click="toggleExpandAll">展开/折叠</el-button>
    </div>

    <el-table
      v-if="refreshTable"
      v-loading="loading"
      :data="menuTable"
      row-key="menuId"
      :default-expand-all="isExpandAll"
      :tree-props="{ children: 'children', hasChildren: 'hasChildren' }"
      border
    >
      <el-table-column label="菜单名称" prop="menuName" min-width="180" show-overflow-tooltip />
      <el-table-column label="图标" width="70" align="center">
        <template #default="{ row }">
          <el-icon v-if="row.icon && row.icon !== '#'"><component :is="row.icon" /></el-icon>
        </template>
      </el-table-column>
      <el-table-column label="排序" prop="orderNum" width="70" align="center" />
      <el-table-column label="权限标识" prop="perms" min-width="150" show-overflow-tooltip />
      <el-table-column label="组件路径" prop="component" min-width="160" show-overflow-tooltip />
      <el-table-column label="状态" width="90" align="center">
        <template #default="{ row }">
          <el-tag :type="row.status === '0' ? 'success' : 'danger'">{{ row.status === '0' ? '正常' : '停用' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="缓存" width="90" align="center">
        <template #default="{ row }">
          <el-tag v-if="row.menuType === 'C'" :type="row.isCache === '0' ? 'primary' : 'info'">
            {{ row.isCache === '0' ? '缓存' : '不缓存' }}
          </el-tag>
          <span v-else>-</span>
        </template>
      </el-table-column>
      <el-table-column label="创建时间" prop="createTime" width="170" />
      <el-table-column label="操作" width="170" align="center" fixed="right" class-name="op-column">
        <template #default="{ row, $index }">
          <el-button v-hasPermi="['system:menu:edit']" link type="primary" icon="Edit" @click="handleUpdate(row)">修改</el-button>
          <el-divider direction="vertical" />
          <el-dropdown :ref="el => setMoreRef(el, $index)" trigger="click" @command="(cmd) => handleAction(cmd, row, $index)">
            <el-button link type="primary" class="op-more-trigger">更多</el-button>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item command="add" icon="Plus" v-hasPermi="['system:menu:add']">新增下级菜单</el-dropdown-item>
                <el-dropdown-item command="delete" icon="Delete" class="danger-item" v-hasPermi="['system:menu:remove']">删除菜单</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </template>
      </el-table-column>
    </el-table>

    <!-- 新增/修改菜单 -->
    <el-dialog v-model="open" :title="title" width="680px" append-to-body>
      <el-form ref="formRef" :model="form" :rules="rules" label-width="100px">
        <el-form-item label="上级菜单">
          <el-tree-select
            v-model="form.parentId"
            :data="menuOptions"
            :props="{ label: 'label', children: 'children' }"
            node-key="id"
            check-strictly
            style="width: 100%"
            placeholder="请选择上级菜单"
          />
        </el-form-item>
        <el-form-item label="菜单类型">
          <el-radio-group v-model="form.menuType">
            <el-radio value="M">目录</el-radio>
            <el-radio value="C">菜单</el-radio>
            <el-radio value="F">按钮</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="菜单名称" prop="menuName">
              <el-input v-model="form.menuName" placeholder="请输入菜单名称" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="显示排序" prop="orderNum">
              <el-input-number v-model="form.orderNum" :min="0" controls-position="right" />
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType !== 'F'" :span="12">
            <el-form-item label="菜单图标">
              <el-input v-model="form.icon" placeholder="如 Setting、User" />
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType !== 'F'" :span="12">
            <el-form-item label="路由地址">
              <el-input v-model="form.path" placeholder="如 user（一级目录为 system）" />
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType === 'C'" :span="24">
            <el-form-item label="组件路径">
              <el-input v-model="form.component" placeholder="如 system/user/index" />
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="权限字符">
              <el-input v-model="form.perms" placeholder="如 system:user:list" />
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType !== 'F'" :span="12">
            <el-form-item label="显示状态">
              <el-radio-group v-model="form.visible">
                <el-radio value="0">显示</el-radio>
                <el-radio value="1">隐藏</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="菜单状态">
              <el-radio-group v-model="form.status">
                <el-radio value="0">正常</el-radio>
                <el-radio value="1">停用</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType === 'C'" :span="24">
            <el-form-item label="是否缓存">
              <el-radio-group v-model="form.isCache">
                <el-radio value="0">缓存</el-radio>
                <el-radio value="1">不缓存</el-radio>
              </el-radio-group>
              <div style="font-size: 12px; color: var(--text-secondary, #909399); line-height: 1.5">
                开启后（keep-alive）切换页签保留查询条件与分页位置；页面组件名需与路由名一致
              </div>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <el-button type="primary" @click="submitForm">确 定</el-button>
        <el-button @click="cancel">取 消</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
defineOptions({ name: 'Menu' })
import { computed, nextTick, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { addMenu, delMenu, getMenu, listMenu, treeselect, updateMenu } from '@/api/system/menu'
import { handleTree } from '@/utils/tree'

const loading = ref(false)
const open = ref(false)
const title = ref('')
const menuList = ref([])
const ids = ref([])
const menuOptions = ref([])
const refreshTable = ref(true)
const isExpandAll = ref(false)
const formRef = ref(null)

const queryParams = reactive({
  menuName: undefined,
  status: undefined
})

const form = reactive({
  menuId: undefined,
  parentId: 0,
  menuName: undefined,
  orderNum: 0,
  path: undefined,
  component: undefined,
  query: undefined,
  isFrame: '1',
  isCache: '0',
  menuType: 'M',
  visible: '0',
  status: '0',
  perms: undefined,
  icon: undefined,
  remark: undefined
})

const rules = {
  menuName: [{ required: true, message: '菜单名称不能为空', trigger: 'blur' }],
  orderNum: [{ required: true, message: '显示顺序不能为空', trigger: 'blur' }]
}

const menuTable = computed(() => handleTree(menuList.value, 'menuId', 'parentId', 'children'))

function getList() {
  loading.value = true
  listMenu(queryParams)
    .then((res) => {
      menuList.value = res.data || []
    })
    .finally(() => {
      loading.value = false
    })
}

function getTreeselect() {
  treeselect().then((res) => {
    menuOptions.value = [{ id: 0, label: '主类目', children: res.data || [] }]
  })
}

function handleQuery() {
  getList()
}

function resetQuery() {
  queryParams.menuName = undefined
  queryParams.status = undefined
  getList()
}

function toggleExpandAll() {
  refreshTable.value = false
  isExpandAll.value = !isExpandAll.value
  nextTick(() => {
    refreshTable.value = true
  })
}

function reset() {
  Object.assign(form, {
    menuId: undefined,
    parentId: 0,
    menuName: undefined,
    orderNum: 0,
    path: undefined,
    component: undefined,
    query: undefined,
    isFrame: '1',
    isCache: '0',
    menuType: 'M',
    visible: '0',
    status: '0',
    perms: undefined,
    icon: undefined,
    remark: undefined
  })
  formRef.value?.clearValidate()
}

function handleAdd(row) {
  reset()
  getTreeselect()
  if (row && row.menuId) {
    form.parentId = row.menuId
  }
  open.value = true
  title.value = '添加菜单'
}

function handleUpdate(row) {
  reset()
  getTreeselect()
  getMenu(row.menuId).then((res) => {
    Object.assign(form, res.data || {})
    open.value = true
    title.value = '修改菜单'
  })
}

function submitForm() {
  formRef.value.validate((valid) => {
    if (!valid) return
    if (form.menuId) {
      updateMenu(form).then(() => {
        ElMessage.success('修改成功')
        open.value = false
        getList()
      })
    } else {
      addMenu(form).then(() => {
        ElMessage.success('新增成功')
        open.value = false
        getList()
      })
    }
  })
}

function cancel() {
  open.value = false
  reset()
}

function handleDelete(row) {
  ElMessageBox.confirm(`是否确认删除名称为"${row.menuName}"的数据项？`, '系统提示', {
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    type: 'warning'
  })
    .then(() => delMenu(row.menuId))
    .then(() => {
      getList()
      ElMessage.success('删除成功')
    })
}

const moreRefs = ref([])
function setMoreRef(el, index) { moreRefs.value[index] = el }
function closeMore() {
  // 兜底：隐藏所有 dropdown 弹出层（含因行 DOM 重建而失联的孤儿弹出层）
  document.querySelectorAll('.el-dropdown__popper').forEach((el) => {
    el.style.display = 'none'
  })
}

function handleAction(command, row, index) {
  closeMore(index)
  if (command === 'add') {
    handleAdd(row)
  } else if (command === 'delete') {
    handleDelete(row)
  }
}

onMounted(() => {
  getList()
  getTreeselect()
})
</script>
