// muyue-react-ui/src/pages/system/notice.jsx
import React, { useEffect, useRef, useState } from 'react'
import {
  PageContainer,
  ProTable,
  ProForm,
  ModalForm,
  ProFormText,
  ProFormTextArea,
  ProFormRadio,
  ProFormSelect
} from '@ant-design/pro-components'
import { App, Button, Descriptions, Modal, Popconfirm, Space, Tag, Typography } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import {
  listNotice,
  getNotice,
  addNotice,
  updateNotice,
  delNotice
} from '../../api/notice'
import Auth from '../../components/Auth'
import { notifyUnread } from '../../utils/noticeBus'

const { Text } = Typography
const typeMap = { 1: { label: '通知', color: 'warning' }, 2: { label: '公告', color: 'success' } }

export default function SystemNotice() {
  const { message, modal } = App.useApp()
  const actionRef = useRef()
  const [formOpen, setFormOpen] = useState(false)
  const [editRow, setEditRow] = useState(null)

  const openDetail = (row) => {
    getNotice(row.noticeId).then((res) => {
      const notice = res.data
      modal.info({
        title: notice.noticeTitle,
        width: 680,
        content: (
          <div>
            <Descriptions column={2} size="small" style={{ marginTop: 16 }}>
              <Descriptions.Item label="类型">
                <Tag color={typeMap[notice.noticeType]?.color}>
                  {typeMap[notice.noticeType]?.label}
                </Tag>
              </Descriptions.Item>
              <Descriptions.Item label="发布时间">{notice.createTime}</Descriptions.Item>
              <Descriptions.Item label="发布人">{notice.createBy}</Descriptions.Item>
              <Descriptions.Item label="状态">
                {notice.status === '0' ? '正常' : '已关闭'}
              </Descriptions.Item>
            </Descriptions>
            <div
              style={{
                marginTop: 16,
                padding: 16,
                background: '#f7f8fa',
                borderRadius: 8,
                whiteSpace: 'pre-wrap',
                lineHeight: 1.8,
                minHeight: 120
              }}
            >
              {notice.noticeContent}
            </div>
          </div>
        )
      })
      // 后端"查看即标记已读"：刷新列表中的已读状态 + 立即联动铃铛角标
      actionRef.current?.reload()
      notifyUnread()
    })
  }

  const handleDelete = (ids) => {
    delNotice(ids.join(',')).then(() => {
      message.success('删除成功')
      actionRef.current?.reload()
      notifyUnread()
    })
  }

  const columns = [
    {
      title: '类型',
      dataIndex: 'noticeType',
      width: 90,
      align: 'center',
      render: (v) => <Tag color={typeMap[v]?.color}>{typeMap[v]?.label || v}</Tag>
    },
    {
      title: '标题',
      dataIndex: 'noticeTitle',
      ellipsis: true,
      render: (v, row) => (
        <Space>
          {row.is_read === 0 && <Badge />}
          <Text strong={row.is_read === 0}>{v}</Text>
        </Space>
      )
    },
    {
      title: '已读状态',
      dataIndex: 'is_read',
      width: 100,
      align: 'center',
      render: (v) =>
        v === 0 ? <Tag color="error">未读</Tag> : <Tag color="default">已读</Tag>
    },
    { title: '发布人', dataIndex: 'createBy', width: 110 },
    { title: '发布时间', dataIndex: 'createTime', width: 170 },
    {
      title: '操作',
      width: 150,
      render: (_, row) => (
        <Space>
          <Auth permi="system:notice:query">
            <a onClick={() => openDetail(row)}>{row.is_read === 0 ? '阅读' : '详情'}</a>
          </Auth>
          <Auth permi="system:notice:edit">
            <a
              onClick={() => {
                setEditRow(row)
                setFormOpen(true)
              }}
            >
              修改
            </a>
          </Auth>
          <Auth permi="system:notice:remove">
            <Popconfirm title="确认删除该公告？" onConfirm={() => handleDelete([row.noticeId])}>
              <a style={{ color: 'red' }}>删除</a>
            </Popconfirm>
          </Auth>
        </Space>
      )
    }
  ]

  return (
    <PageContainer>
      <ProTable
        rowKey="noticeId"
        actionRef={actionRef}
        columns={columns}
        cardBordered
        search={{ labelWidth: 'auto' }}
        pagination={{ defaultPageSize: 10 }}
        request={async (params) => {
          const { current, pageSize, ...rest } = params
          const res = await listNotice({ ...rest, pageNum: current, pageSize })
          return { data: res.rows, total: res.total, success: true }
        }}
        toolBarRender={() => [
          <Auth key="add" permi="system:notice:add">
            <Button
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => {
                setEditRow(null)
                setFormOpen(true)
              }}
            >
              发布公告
            </Button>
          </Auth>
        ]}
      />

      <NoticeForm
        editRow={editRow}
        open={formOpen}
        setOpen={setFormOpen}
        onDone={() => {
          actionRef.current?.reload()
          notifyUnread()
        }}
      />
    </PageContainer>
  )
}

function Badge() {
  return <span style={{ width: 8, height: 8, background: '#ff4d4f', borderRadius: '50%', display: 'inline-block' }} />
}

function NoticeForm({ open, setOpen, editRow, onDone }) {
  const { message } = App.useApp()
  const [form] = ProForm.useForm()

  useEffect(() => {
    if (open) {
      if (editRow) {
        getNotice(editRow.noticeId).then((res) => {
          form.setFieldsValue(res.data)
        })
      } else {
        form.resetFields()
        form.setFieldsValue({ noticeType: '1', status: '0' })
      }
    }
  }, [open])

  return (
    <ModalForm
      title={editRow ? '修改公告' : '发布公告'}
      open={open}
      form={form}
      width={640}
      modalProps={{ destroyOnClose: true }}
      onOpenChange={setOpen}
      onFinish={async (values) => {
        const action = editRow ? updateNotice({ ...editRow, ...values }) : addNotice(values)
        await action
        message.success(editRow ? '修改成功' : '发布成功')
        onDone()
        return true
      }}
    >
      <ProFormRadio.Group
        name="noticeType"
        label="公告类型"
        options={[
          { label: '通知', value: '1' },
          { label: '公告', value: '2' }
        ]}
        rules={[{ required: true }]}
      />
      <ProFormText
        name="noticeTitle"
        label="标题"
        rules={[{ required: true, message: '标题不能为空' }]}
      />
      <ProFormRadio.Group
        name="status"
        label="状态"
        options={[
          { label: '正常', value: '0' },
          { label: '关闭', value: '1' }
        ]}
      />
      <ProFormTextArea
        name="noticeContent"
        label="内容"
        fieldProps={{ rows: 8 }}
        rules={[{ required: true, message: '内容不能为空' }]}
      />
    </ModalForm>
  )
}

// muyue-ui/src/views/system/notice/index.vue
<template>
  <div class="app-container">
    <el-form :model="queryParams" ref="queryRef" :inline="true" class="search-form">
      <el-form-item label="公告标题" prop="noticeTitle">
        <el-input v-model="queryParams.noticeTitle" placeholder="请输入公告标题" clearable @keyup.enter="handleQuery" />
      </el-form-item>
      <el-form-item label="公告类型" prop="noticeType">
        <el-select v-model="queryParams.noticeType" placeholder="公告类型" clearable style="width: 120px">
          <el-option label="通知" value="1" />
          <el-option label="公告" value="2" />
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" :icon="Search" @click="handleQuery">搜索</el-button>
        <el-button :icon="Refresh" @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <el-row :gutter="10" class="table-toolbar">
      <el-col :span="1.5">
        <el-button type="primary" plain :icon="Plus" v-hasPermi="['system:notice:add']" @click="handleAdd">新增</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="danger" plain :icon="Delete" :disabled="!selectedIds.length" v-hasPermi="['system:notice:remove']" @click="handleDelete">删除</el-button>
      </el-col>
    </el-row>

    <el-table :data="noticeList" v-loading="loading" border @selection-change="handleSelectionChange" class="page-container">
      <el-table-column type="selection" width="50" align="center" />
      <el-table-column label="公告编号" prop="noticeId" width="100" align="center" />
      <el-table-column label="公告标题">
        <template #default="{ row }">
          <el-link type="primary" @click="handleView(row)">{{ row.noticeTitle }}</el-link>
        </template>
      </el-table-column>
      <el-table-column label="公告类型" width="100" align="center">
        <template #default="{ row }">
          <el-tag :type="row.noticeType === '1' ? 'warning' : 'success'">{{ row.noticeType === '1' ? '通知' : '公告' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="状态" width="90" align="center">
        <template #default="{ row }">
          <el-tag :type="row.status === '0' ? 'primary' : 'info'">{{ row.status === '0' ? '正常' : '关闭' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="创建者" prop="createBy" width="100" align="center" />
      <el-table-column label="状态" width="90" align="center">
        <template #default="{ row }">
          <el-tag v-if="row.isRead === 1" type="info" effect="plain">已读</el-tag>
          <el-tag v-else type="danger" effect="dark">未读</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="创建时间" prop="createTime" width="180" />
      <el-table-column label="操作" width="150" align="center" class-name="op-column">
        <template #default="{ row }">
          <el-button link type="primary" :icon="View" v-hasPermi="['system:notice:query']" @click="handleView(row)">详情</el-button>
          <el-divider direction="vertical" />
          <el-dropdown trigger="click" @command="(cmd) => handleAction(cmd, row)">
            <span class="op-more">
              更多<el-icon class="el-icon--right"><ArrowDown /></el-icon>
            </span>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item command="edit" icon="Edit" v-hasPermi="['system:notice:edit']">修改公告</el-dropdown-item>
                <el-dropdown-item command="delete" icon="Delete" class="danger-item" v-hasPermi="['system:notice:remove']">删除公告</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </template>
      </el-table-column>
    </el-table>

    <pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />

    <!-- 公告详情 -->
    <el-dialog :title="viewNotice?.noticeTitle" v-model="viewOpen" width="700px" append-to-body>
      <el-descriptions :column="2" border>
        <el-descriptions-item label="公告类型">
          <el-tag :type="viewNotice?.noticeType === '1' ? 'warning' : 'success'">{{ viewNotice?.noticeType === '1' ? '通知' : '公告' }}</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="发布时间">{{ viewNotice?.createTime }}</el-descriptions-item>
      </el-descriptions>
      <div class="notice-content">{{ viewNotice?.noticeContent }}</div>
      <div class="notice-footer">—— {{ viewNotice?.createBy }} 发布</div>
    </el-dialog>

    <!-- 新增/修改公告 -->
    <el-dialog :title="title" v-model="open" width="680px" append-to-body>
      <el-form :model="form" :rules="rules" ref="formRef" label-width="80px">
        <el-form-item label="公告类型" prop="noticeType">
          <el-radio-group v-model="form.noticeType">
            <el-radio value="1">通知</el-radio>
            <el-radio value="2">公告</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="公告标题" prop="noticeTitle">
          <el-input v-model="form.noticeTitle" placeholder="请输入公告标题" />
        </el-form-item>
        <el-form-item label="状态" prop="status">
          <el-radio-group v-model="form.status">
            <el-radio value="0">正常</el-radio>
            <el-radio value="1">关闭</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="公告内容" prop="noticeContent">
          <el-input v-model="form.noticeContent" type="textarea" :rows="8" placeholder="请输入公告内容" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="cancel">取 消</el-button>
        <el-button type="primary" @click="submitForm">发 布</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search, Refresh, Plus, Delete, Edit, View } from '@element-plus/icons-vue'
import { listNotice, getNotice, addNotice, updateNotice, delNotice } from '@/api/system/notice'

const loading = ref(false)
const noticeList = ref([])
const total = ref(0)
const open = ref(false)
const viewOpen = ref(false)
const viewNotice = ref(null)
const title = ref('')
const selectedIds = ref([])
const queryRef = ref()
const formRef = ref()

const queryParams = reactive({ pageNum: 1, pageSize: 10, noticeTitle: '', noticeType: '' })
const defaultForm = { noticeId: undefined, noticeTitle: '', noticeType: '1', noticeContent: '', status: '0' }
const form = reactive({ ...defaultForm })
const rules = {
  noticeTitle: [{ required: true, message: '公告标题不能为空', trigger: 'blur' }],
  noticeContent: [{ required: true, message: '公告内容不能为空', trigger: 'blur' }]
}

function getList() {
  loading.value = true
  listNotice(queryParams).then((res) => {
    noticeList.value = res.rows
    total.value = res.total
    loading.value = false
  })
}
function handleQuery() {
  queryParams.pageNum = 1
  getList()
}
function resetQuery() {
  queryRef.value.resetFields()
  handleQuery()
}
function handleSelectionChange(rows) {
  selectedIds.value = rows.map((r) => r.noticeId)
}
function reset() {
  Object.assign(form, defaultForm)
}
function handleAdd() {
  reset()
  open.value = true
  title.value = '发布公告'
}
function handleUpdate(row) {
  reset()
  getNotice(row.noticeId).then((res) => {
    Object.assign(form, res.data)
    open.value = true
    title.value = '修改公告'
  })
}
function handleView(row) {
  getNotice(row.noticeId).then((res) => {
    viewNotice.value = res.data
    viewOpen.value = true
    // 后端已标记已读，刷新列表状态
    getList()
  })
}
function cancel() {
  open.value = false
}
function submitForm() {
  formRef.value.validate((valid) => {
    if (!valid) return
    const action = form.noticeId ? updateNotice(form) : addNotice(form)
    action.then(() => {
      ElMessage.success(form.noticeId ? '修改成功' : '发布成功')
      open.value = false
      getList()
    })
  })
}
function handleDelete(row) {
  const ids = row.noticeId ? [row.noticeId] : selectedIds.value
  ElMessageBox.confirm('是否确认删除公告编号为"' + ids.join(',') + '"的数据项？', '提示', {
    type: 'warning'
  }).then(() => delNotice(ids.join(','))).then(() => {
    ElMessage.success('删除成功')
    getList()
  })
}

function handleAction(command, row) {
  if (command === 'edit') {
    handleUpdate(row)
  } else if (command === 'delete') {
    handleDelete(row)
  }
}

onMounted(getList)
</script>

<style scoped>
.app-container {
  padding: 18px;
}
.notice-content {
  margin-top: 16px;
  padding: 16px;
  line-height: 1.8;
  font-size: 14px;
  color: var(--text-regular);
  background: var(--bg-hover);
  border-radius: 8px;
  white-space: pre-wrap;
  word-break: break-all;
}
.notice-footer {
  margin-top: 12px;
  text-align: right;
  font-size: 13px;
  color: var(--text-secondary);
}
</style>
