// muyue-react-ui/src/pages/system/dept.jsx
import React, { useRef, useState } from 'react'
import {
  PageContainer, ModalForm, ProFormText, ProFormRadio,
  ProFormTreeSelect, ProFormTextArea
} from '@ant-design/pro-components'
import { App, Popconfirm, Space, Table, Tag } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { listDept, getDept, addDept, updateDept, delDept, deptTreeSelect } from '../../api/dept'
import Auth from '../../components/Auth'

function toTreeData(nodes) {
  return (nodes || []).map((n) => ({
    title: n.label, value: n.id, key: n.id,
    children: toTreeData(n.children)
  }))
}

/** 扁平列表 → 树（后端 dept/list 返回平铺，需前端组树） */
function buildTree(list, idKey, parentKey) {
  const map = {}
  const input = list || []
  input.forEach((item) => {
    map[item[idKey]] = { ...item, key: item[idKey], children: [] }
  })
  const roots = []
  input.forEach((item) => {
    const node = map[item[idKey]]
    const parent = map[item[parentKey]]
    if (parent && item[parentKey] !== item[idKey]) {
      parent.children.push(node)
    } else {
      roots.push(node)
    }
  })
  const prune = (nodes) =>
    nodes.map((n) => {
      const next = { ...n }
      if (next.children.length) {
        next.children = prune(next.children)
      } else {
        delete next.children
      }
      return next
    })
  return prune(roots)
}

export default function SystemDept() {
  const { message } = App.useApp()
  const [rows, setRows] = useState([])
  const [expandedKeys, setExpandedKeys] = useState([])
  const [loading, setLoading] = useState(true)
  const [formOpen, setFormOpen] = useState(false)
  const [editRow, setEditRow] = useState(null)
  const [treeData, setTreeData] = useState([])

  const collectKeys = (nodes) =>
    (nodes || []).flatMap((n) => (n.children && n.children.length ? [n.key, ...collectKeys(n.children)] : []))

  const load = () => {
    setLoading(true)
    listDept().then((res) => {
      const tree = buildTree(res.data, 'deptId', 'parentId')
      setRows(tree)
      setExpandedKeys(collectKeys(tree))
      setLoading(false)
    })
  }

  React.useEffect(load, [])

  const openForm = async (row, parentId) => {
    setEditRow(row ? { ...row, parentId: row.parentId } : { parentId: parentId ?? 0 })
    setFormOpen(true)
    const tree = await deptTreeSelect()
    setTreeData(toTreeData(tree.data))
    if (row) {
      const detail = await getDept(row.deptId)
      setEditRow(detail.data)
    }
  }

  const columns = [
    { title: '部门名称', dataIndex: 'deptName', width: 260 },
    { title: '排序', dataIndex: 'orderNum', width: 80, align: 'center' },
    { title: '负责人', dataIndex: 'leader', width: 110 },
    { title: '联系电话', dataIndex: 'phone', width: 140 },
    { title: '邮箱', dataIndex: 'email', ellipsis: true },
    {
      title: '状态', dataIndex: 'status', width: 90, align: 'center',
      render: (v) => <Tag color={v === '0' ? 'success' : 'default'}>{v === '0' ? '正常' : '停用'}</Tag>
    },
    { title: '创建时间', dataIndex: 'createTime', width: 170 },
    {
      title: '操作', width: 180,
      render: (_, row) => (
        <Space>
          <Auth permi="system:dept:add">
            <a onClick={() => openForm(null, row.deptId)}><PlusOutlined /> 新增</a>
          </Auth>
          <Auth permi="system:dept:edit">
            <a onClick={() => openForm(row)}>修改</a>
          </Auth>
          <Auth permi="system:dept:remove">
            <Popconfirm title="确认删除该部门？" onConfirm={() =>
              delDept(row.deptId).then(() => { message.success('删除成功'); load() })
            }>
              <a style={{ color: 'red' }}>删除</a>
            </Popconfirm>
          </Auth>
        </Space>
      )
    }
  ]

  return (
    <PageContainer>
      <div style={{ marginBottom: 12 }}>
        <Auth permi="system:dept:add">
          <a onClick={() => openForm(null, 0)}><PlusOutlined /> 新增顶级部门</a>
        </Auth>
      </div>
      <Table
        rowKey="deptId"
        columns={columns}
        dataSource={rows}
        loading={loading}
        pagination={false}
        expandedKeys={expandedKeys}
        onExpandedRowsChange={setExpandedKeys}
      />

      <ModalForm
        title={editRow && editRow.deptId ? '修改部门' : '新增部门'}
        open={formOpen}
        onOpenChange={setFormOpen}
        width={560}
        modalProps={{ destroyOnClose: true }}
        initialValues={editRow}
        key={formOpen ? (editRow && editRow.deptId ? 'e' + editRow.deptId : 'a' + (editRow && editRow.parentId)) : 'closed'}
        onFinish={async (values) => {
          if (editRow && editRow.deptId) {
            await updateDept({ deptId: editRow.deptId, parentId: editRow.parentId, ...values })
            message.success('修改成功')
          } else {
            await addDept({ parentId: editRow.parentId, ...values })
            message.success('新增成功')
          }
          load()
          return true
        }}
      >
        <ProFormTreeSelect
          name="parentId" label="上级部门"
          fieldProps={{ treeData, fieldNames: { label: 'title', value: 'value', children: 'children' } }}
          rules={[{ required: true, message: '请选择上级部门' }]}
        />
        <ProFormText name="deptName" label="部门名称" rules={[{ required: true }]} />
        <ProFormText name="orderNum" label="显示排序" rules={[{ required: true }]} />
        <ProFormText name="leader" label="负责人" />
        <ProFormText name="phone" label="联系电话" />
        <ProFormText name="email" label="邮箱" />
        <ProFormRadio.Group
          name="status" label="状态"
          options={[{ label: '正常', value: '0' }, { label: '停用', value: '1' }]}
        />
      </ModalForm>
    </PageContainer>
  )
}

// muyue-ui/src/views/system/dept/index.vue
<template>
  <div class="page-container">
    <el-form :model="queryParams" :inline="true" class="search-form">
      <el-form-item label="部门名称">
        <el-input v-model="queryParams.deptName" placeholder="请输入部门名称" clearable style="width: 180px" @keyup.enter="handleQuery" />
      </el-form-item>
      <el-form-item label="状态">
        <el-select v-model="queryParams.status" placeholder="请选择" clearable style="width: 110px">
          <el-option label="正常" value="0" />
          <el-option label="停用" value="1" />
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
        <el-button icon="Refresh" @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <div class="table-toolbar">
      <el-button v-hasPermi="['system:dept:add']" type="primary" icon="Plus" @click="handleAdd">新增</el-button>
      <el-button icon="Sort" @click="toggleExpandAll">展开/折叠</el-button>
    </div>

    <el-table
      v-if="refreshTable"
      v-loading="loading"
      :data="deptTable"
      row-key="deptId"
      :default-expand-all="isExpandAll"
      :tree-props="{ children: 'children', hasChildren: 'hasChildren' }"
      border
    >
      <el-table-column label="部门名称" prop="deptName" min-width="180" />
      <el-table-column label="排序" prop="orderNum" width="70" align="center" />
      <el-table-column label="负责人" prop="leader" width="100" />
      <el-table-column label="联系电话" prop="phone" width="130" />
      <el-table-column label="邮箱" prop="email" min-width="160" />
      <el-table-column label="状态" width="90" align="center">
        <template #default="{ row }">
          <el-tag :type="row.status === '0' ? 'success' : 'danger'">{{ row.status === '0' ? '正常' : '停用' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="创建时间" prop="createTime" width="170" />
      <el-table-column label="操作" width="150" align="center" fixed="right" class-name="op-column">
        <template #default="{ row }">
          <el-button v-hasPermi="['system:dept:edit']" link type="primary" icon="Edit" @click="handleUpdate(row)">修改</el-button>
          <el-divider direction="vertical" />
          <el-dropdown trigger="click" @command="(cmd) => handleAction(cmd, row)">
            <span class="op-more">
              更多<el-icon class="el-icon--right"><ArrowDown /></el-icon>
            </span>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item command="add" icon="Plus" v-hasPermi="['system:dept:add']">新增下级部门</el-dropdown-item>
                <el-dropdown-item command="delete" icon="Delete" class="danger-item" v-hasPermi="['system:dept:remove']">删除部门</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </template>
      </el-table-column>
    </el-table>

    <!-- 新增/修改部门 -->
    <el-dialog v-model="open" :title="title" width="600px" append-to-body>
      <el-form ref="formRef" :model="form" :rules="rules" label-width="90px">
        <el-form-item label="上级部门">
          <el-tree-select
            v-model="form.parentId"
            :data="deptOptions"
            :props="{ label: 'label', children: 'children' }"
            node-key="id"
            check-strictly
            style="width: 100%"
            placeholder="请选择上级部门"
          />
        </el-form-item>
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="部门名称" prop="deptName">
              <el-input v-model="form.deptName" placeholder="请输入部门名称" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="显示排序" prop="orderNum">
              <el-input-number v-model="form.orderNum" :min="0" controls-position="right" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="负责人">
              <el-input v-model="form.leader" maxlength="20" placeholder="请输入负责人" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="联系电话">
              <el-input v-model="form.phone" maxlength="11" placeholder="请输入联系电话" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="邮箱">
              <el-input v-model="form.email" maxlength="50" placeholder="请输入邮箱" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="部门状态">
              <el-radio-group v-model="form.status">
                <el-radio value="0">正常</el-radio>
                <el-radio value="1">停用</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <el-button type="primary" @click="submitForm">确 定</el-button>
        <el-button @click="cancel">取 消</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, nextTick, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { addDept, delDept, deptTreeSelect, getDept, listDept, updateDept } from '@/api/system/dept'
import { handleTree } from '@/utils/tree'

const loading = ref(false)
const open = ref(false)
const title = ref('')
const deptList = ref([])
const deptOptions = ref([])
const refreshTable = ref(true)
const isExpandAll = ref(true)
const formRef = ref(null)

const queryParams = reactive({
  deptName: undefined,
  status: undefined
})

const form = reactive({
  deptId: undefined,
  parentId: 0,
  deptName: undefined,
  orderNum: 0,
  leader: undefined,
  phone: undefined,
  email: undefined,
  status: '0'
})

const rules = {
  deptName: [{ required: true, message: '部门名称不能为空', trigger: 'blur' }],
  orderNum: [{ required: true, message: '显示顺序不能为空', trigger: 'blur' }]
}

const deptTable = computed(() => handleTree(deptList.value, 'deptId', 'parentId', 'children'))

function getList() {
  loading.value = true
  listDept(queryParams)
    .then((res) => {
      deptList.value = res.data || []
    })
    .finally(() => {
      loading.value = false
    })
}

function getTreeselect() {
  deptTreeSelect().then((res) => {
    deptOptions.value = [{ id: 0, label: '主类目', children: res.data || [] }]
  })
}

function handleQuery() {
  getList()
}

function resetQuery() {
  queryParams.deptName = undefined
  queryParams.status = undefined
  getList()
}

function toggleExpandAll() {
  refreshTable.value = false
  isExpandAll.value = !isExpandAll.value
  nextTick(() => {
    refreshTable.value = true
  })
}

function reset() {
  Object.assign(form, {
    deptId: undefined,
    parentId: 0,
    deptName: undefined,
    orderNum: 0,
    leader: undefined,
    phone: undefined,
    email: undefined,
    status: '0'
  })
  formRef.value?.clearValidate()
}

function handleAdd(row) {
  reset()
  getTreeselect()
  if (row && row.deptId) {
    form.parentId = row.deptId
  }
  open.value = true
  title.value = '添加部门'
}

function handleUpdate(row) {
  reset()
  getTreeselect()
  getDept(row.deptId).then((res) => {
    Object.assign(form, res.data || {})
    open.value = true
    title.value = '修改部门'
  })
}

function submitForm() {
  formRef.value.validate((valid) => {
    if (!valid) return
    if (form.deptId) {
      updateDept(form).then(() => {
        ElMessage.success('修改成功')
        open.value = false
        getList()
      })
    } else {
      addDept(form).then(() => {
        ElMessage.success('新增成功')
        open.value = false
        getList()
        getTreeselect()
      })
    }
  })
}

function cancel() {
  open.value = false
  reset()
}

function handleDelete(row) {
  ElMessageBox.confirm(`是否确认删除名称为"${row.deptName}"的数据项？`, '系统提示', {
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    type: 'warning'
  })
    .then(() => delDept(row.deptId))
    .then(() => {
      getList()
      getTreeselect()
      ElMessage.success('删除成功')
    })
}

function handleAction(command, row) {
  if (command === 'add') {
    handleAdd(row)
  } else if (command === 'delete') {
    handleDelete(row)
  }
}

onMounted(() => {
  getList()
  getTreeselect()
})
</script>
